apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-media-pv
  namespace: onnasoft
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/media-onnasoft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - juliotorres-pc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-media-pvc
  namespace: onnasoft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
